apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-dep-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:        # <-- must be plural 'requests'
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: main-db-storage
          mountPath: /usr/share/nginx/html
          # mountPath: /var/www/html
      volumes:
      - name: main-db-storage
        persistentVolumeClaim:
          claimName: local-pvc
  strategy:
    type: Recreate
