apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==        # 'root'
  MYSQL_DATABASE: ZGV2b3Bz             # 'devops'
  MYSQL_ALLOW_EMPTY_PASSWORD: bm8=     # 'no'
